# 携帯電話価格帯分類のコンペの前情報

## 前処理

In [2]:
#必要なライブラリのインストール
import pandas as pd

In [3]:
train_filename = "../data/train.csv"
test_filename = "../data/test.csv"
#データの読み込み
train = pd.read_csv(train_filename) 
test= pd.read_csv(test_filename)

### 学習用データとテスト用データの確認

In [4]:
train.head()

,id,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,0,1203,0,0.680981,1,1,1,23,0.402580,117,...,1331,721,1970,15,1,4,1,0,1,2
1,3,1203,1,2.602754,1,0,0,8,0.415612,194,...,1571,1262,1150,14,16,14,1,0,1,3
2,4,1980,1,2.604065,1,0,0,6,0.858110,122,...,364,721,1970,18,12,11,1,0,1,1
3,5,1185,1,2.669403,1,3,0,33,0.027065,132,...,447,1162,1950,15,3,19,1,0,0,2
4,7,1203,1,2.375453,0,4,1,12,0.141485,135,...,364,1917,1970,16,7,6,1,1,1,0

In [7]:
test.head()

,id,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,...,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
0,1,1203,0,0.498993,1,0,1,40,0.914530,190,...,7,381,721,1970,6,1,2,1,0,1
1,2,1154,0,1.981014,0,1,0,33,0.025999,82,...,10,376,1555,1970,11,7,3,1,0,0
2,6,1027,1,1.647026,0,0,1,32,0.912318,103,...,1,364,1374,1970,17,1,6,1,0,0
3,10,833,0,1.070061,0,0,0,2,0.033010,156,...,0,1331,1710,832,12,8,8,1,1,0
4,12,1027,1,1.859165,0,4,1,2,0.612349,171,...,13,667,1642,2655,14,5,2,1,1,0

In [9]:
# データの基本情報を表示
print(train.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             1200 non-null   int64
 1   battery_power  1200 non-null   int64
 2   blue           1200 non-null   int64
 3   clock_speed    1200 non-null   float64
 4   dual_sim       1200 non-null   int64
 5   fc             1200 non-null   int64
 6   four_g         1200 non-null   int64
 7   int_memory     1200 non-null   int64
 8   m_dep          1200 non-null   float64
 9   mobile_wt      1200 non-null   int64
 10  n_cores        1200 non-null   int64
 11  pc             1200 non-null   int64
 12  px_height      1200 non-null   int64
 13  px_width       1200 non-null   int64
 14  ram            1200 non-null   int64
 15  sc_h           1200 non-null   int64
 16  sc_w           1200 non-null   int64
 17  talk_time      1200 non-null   int64
 18  three_g        1200 non-null   int64
 19  touch_screen   1200 non-null   int64
 20  wifi           1200 non-null   int64
 21  price_range    1200 non-null   int64
dtypes: float64(2), int64(20)
memory usage: 206.4 KB
None

In [10]:
# データの統計情報を表示
print(train.describe())

                id  battery_power         blue  clock_speed     dual_sim  \
count  1200.000000    1200.000000  1200.000000  1200.000000  1200.000000
mean   1014.411667    1208.958333     0.408333     1.231201     0.565833
std     577.846419     421.707099     0.491730     0.786728     0.495854
min       0.000000     518.000000     0.000000     0.466459     0.000000
25%     517.750000     916.000000     0.000000     0.498935     0.000000
50%    1030.500000    1203.000000     0.000000     1.086733     1.000000
75%    1504.250000    1537.000000     1.000000     1.864943     1.000000
max    1999.000000    1991.000000     1.000000     2.730560     1.000000

                fc       four_g   int_memory        m_dep    mobile_wt  ...  \
count  1200.000000  1200.000000  1200.000000  1200.000000  1200.000000  ...
mean      1.452500     0.625833    29.747500     0.374023   137.475833  ...
std       2.590045     0.484109    17.514071     0.322579    34.706169  ...
min       0.000000     0.000000     2.000000     0.013852    80.000000  ...
25%       0.000000     0.000000    15.000000     0.036577   105.000000  ...
50%       0.000000     1.000000    28.000000     0.351939   135.000000  ...
75%       2.000000     1.000000    45.000000     0.798296   168.000000  ...
max      16.000000     1.000000    64.000000     0.939585   199.000000  ...

         px_height     px_width          ram         sc_h         sc_w  \
count  1200.000000  1200.000000  1200.000000  1200.000000  1200.000000
mean    552.335000  1411.056667  1931.339167    11.970000     4.717500
std     419.165889   467.548272  1157.539911     4.304595     3.346445
min       4.000000   510.000000   267.000000     5.000000     0.000000
25%     272.000000  1011.000000   790.000000     7.000000     2.000000
50%     381.000000  1456.000000  1970.000000    12.000000     4.000000
75%     788.000000  1917.000000  3269.000000    16.000000     7.000000
max    1858.000000  1988.000000  3952.000000    19.000000    16.000000

         talk_time      three_g  touch_screen         wifi  price_range
count  1200.000000  1200.000000   1200.000000  1200.000000  1200.000000
mean     10.376667     0.891667      0.410833     0.455000     1.620000
std       5.180942     0.310931      0.492190     0.498179     1.018069
min       2.000000     0.000000      0.000000     0.000000     0.000000
25%       7.000000     1.000000      0.000000     0.000000     1.000000
50%       9.000000     1.000000      0.000000     0.000000     2.000000
75%      14.000000     1.000000      1.000000     1.000000     2.000000
max      20.000000     1.000000      1.000000     1.000000     3.000000

[8 rows x 22 columns]

In [11]:

# 欠損値の確認
print(train.isnull().sum())

id               0
battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64